import { useInternetIdentity } from "@caffeineai/core-infrastructure";
import {
  AlertCircle,
  ArrowDownToLine,
  ArrowUpFromLine,
  CheckCircle2,
  ChevronDown,
  Copy,
  ExternalLink,
  Gamepad2,
  HelpCircle,
  LogIn,
  Shield,
  Sparkles,
  UserPlus,
  Wallet,
} from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { useGetOfficialWallets } from "../hooks/useQueries";
import { OFFICIAL_WALLETS } from "../types";
import { Badge } from "./ui/badge";
import { Button } from "./ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "./ui/card";

interface UserGuideProps {
  onNavigate?: (view: "wallet" | "lobby") => void;
}

const FAQS = [
  {
    q: "What is ICP?",
    a: "ICP (Internet Computer Protocol) is a real cryptocurrency native to the Internet Computer blockchain. It has real monetary value and can be bought on exchanges like Binance, Coinbase, and Kraken. In LudoVerse ICP, you bet and win real ICP coins.",
  },
  {
    q: "Is my ICP safe in LudoVerse?",
    a: "Yes. Your ICP is secured by the Internet Computer blockchain and linked directly to your Internet Identity. Only you can control your account. The canister code is transparent and auditable. We never hold custody of your private keys.",
  },
  {
    q: "How is the dice provably fair?",
    a: "LudoVerse uses Quantum Dice — a world-first provably fair dice system. Every roll generates a seed hash using on-chain entropy. The seed hash is shown to you before the result, and you can verify any roll on the IC blockchain. No centralized server ever controls the outcome.",
  },
  {
    q: "What is a Principal ID?",
    a: "Your Principal ID is your unique address on the Internet Computer — like a bank account number for ICP. It's generated by your Internet Identity and is permanent. You use it to receive ICP deposits from exchanges or other wallets.",
  },
  {
    q: "What is Demo Mode?",
    a: "Demo Mode lets you play Ludo using free virtual Demo Credits (DC) — no real ICP required. You get the exact same game experience including animations, AI Oracle, and Token Soul XP. Perfect for learning the game before risking real ICP.",
  },
  {
    q: "Can I withdraw my winnings anytime?",
    a: "Yes. Your ICP balance is always accessible in the Wallet section. You can withdraw to any ICP-compatible wallet or exchange at any time. Withdrawals process through the ICP ledger in 1–2 minutes.",
  },
];

const STEPS = [
  {
    num: 1,
    icon: <LogIn className="w-5 h-5" />,
    title: "Login with Internet Identity",
    color: "#60a5fa",
    description: "Your secure, password-free blockchain login",
    content: (
      <div className="space-y-3">
        <p className="text-sm text-muted-foreground">
          Internet Identity is the Internet Computer's built-in,
          privacy-preserving authentication system. It's free to create and
          requires no password.
        </p>
        <ol className="space-y-2">
          {[
            'Click the "Login" button in the top-right corner of LudoVerse',
            'A popup window will open — select "Create Internet Identity" if new, or log in with your existing anchor',
            "Use your device's biometrics (fingerprint or Face ID) or a security key",
            "Authorize LudoVerse and you'll be instantly logged in",
          ].map((step, i) => (
            <li
              // biome-ignore lint/suspicious/noArrayIndexKey: static ordered list
              key={i}
              className="flex items-start gap-2 text-sm text-muted-foreground"
            >
              <span className="text-blue-400 font-bold shrink-0">{i + 1}.</span>
              {step}
            </li>
          ))}
        </ol>
        <div className="flex items-start gap-2 p-3 rounded-lg bg-blue-500/10 border border-blue-500/20 text-xs">
          <Shield className="w-4 h-4 text-blue-400 shrink-0 mt-0.5" />
          <p className="text-blue-200/80">
            Internet Identity never shares personal data. Your identity is
            anonymous and cryptographically secure on-chain.
          </p>
        </div>
      </div>
    ),
  },
  {
    num: 2,
    icon: <UserPlus className="w-5 h-5" />,
    title: "Create Your Player Profile",
    color: "#a855f7",
    description: "Pick your name, color, and enter the arena",
    content: (
      <div className="space-y-3">
        <p className="text-sm text-muted-foreground">
          After logging in, you'll be prompted to set up your player profile.
          This is your permanent identity in LudoVerse.
        </p>
        <ol className="space-y-2">
          {[
            "Enter your player name (2–20 characters) — this shows during games",
            "Choose one of 6 futuristic neon colors for your game tokens",
            'Click "Create Profile" — your profile is saved on the blockchain instantly',
          ].map((step, i) => (
            <li
              // biome-ignore lint/suspicious/noArrayIndexKey: static ordered list
              key={i}
              className="flex items-start gap-2 text-sm text-muted-foreground"
            >
              <span className="text-purple-400 font-bold shrink-0">
                {i + 1}.
              </span>
              {step}
            </li>
          ))}
        </ol>
      </div>
    ),
  },
  {
    num: 3,
    icon: <Wallet className="w-5 h-5" />,
    title: "Get Your Wallet Address",
    color: "#22d3ee",
    description: "Find your unique Principal ID for receiving ICP",
    content: (
      <div className="space-y-3">
        <p className="text-sm text-muted-foreground">
          Go to{" "}
          <span className="text-cyan-300 font-medium">Wallet → Deposit</span> to
          see your personal Principal ID.
        </p>
        <div className="p-3 rounded-lg bg-cyan-500/10 border border-cyan-500/20 text-xs space-y-1">
          <p className="text-cyan-300 font-semibold">
            Your Principal ID looks like:
          </p>
          <code className="font-mono text-muted-foreground">
            xxxxx-xxxxx-xxxxx-xxxxx-cai
          </code>
        </div>
        <ol className="space-y-2">
          {[
            "Navigate to Wallet in the menu",
            "Click the Deposit tab",
            "Click the Copy button next to your Principal ID",
            "This is your ICP deposit address — send it to anyone or paste it in your exchange",
          ].map((step, i) => (
            <li
              // biome-ignore lint/suspicious/noArrayIndexKey: static ordered list
              key={i}
              className="flex items-start gap-2 text-sm text-muted-foreground"
            >
              <span className="text-cyan-400 font-bold shrink-0">{i + 1}.</span>
              {step}
            </li>
          ))}
        </ol>
      </div>
    ),
  },
  {
    num: 4,
    icon: <ArrowDownToLine className="w-5 h-5" />,
    title: "Deposit ICP Coins",
    color: "#4ade80",
    description: "Send ICP from Binance, Coinbase, Kraken, or any ICP wallet",
    content: (
      <div className="space-y-4">
        <p className="text-sm text-muted-foreground">
          You need real ICP coins to play live betting games. Here's how to get
          them into LudoVerse:
        </p>
        <div className="space-y-3">
          {[
            {
              title: "From an Exchange (Binance, Coinbase, Kraken)",
              steps: [
                "Log in to your exchange account",
                "Go to Withdrawals → Cryptocurrency → ICP",
                "Paste your LudoVerse Principal ID as the destination address",
                "Enter the amount (minimum 1 ICP) and confirm the withdrawal",
                "Your LudoVerse balance updates in 1–2 minutes",
              ],
              color: "#4ade80",
            },
            {
              title: "From an ICP Wallet (NNS, Plug, Stoic, Bitfinity)",
              steps: [
                "Open your ICP wallet app",
                "Go to Send / Transfer",
                "Paste your LudoVerse Principal ID as the recipient",
                "Enter the amount and confirm",
                "Balance appears in LudoVerse within 1–2 minutes",
              ],
              color: "#22d3ee",
            },
          ].map((method) => (
            <div
              key={method.title}
              className="rounded-xl border p-3 space-y-2"
              style={{
                borderColor: `${method.color}25`,
                background: `${method.color}08`,
              }}
            >
              <p
                className="text-sm font-semibold"
                style={{ color: method.color }}
              >
                {method.title}
              </p>
              <ol className="space-y-1">
                {method.steps.map((step, i) => (
                  <li
                    // biome-ignore lint/suspicious/noArrayIndexKey: static ordered list
                    key={i}
                    className="flex items-start gap-2 text-xs text-muted-foreground"
                  >
                    <span
                      className="font-bold shrink-0"
                      style={{ color: method.color }}
                    >
                      {i + 1}.
                    </span>
                    {step}
                  </li>
                ))}
              </ol>
            </div>
          ))}
        </div>
        <div className="flex items-start gap-2 p-3 rounded-lg bg-yellow-500/10 border border-yellow-500/20 text-xs">
          <AlertCircle className="w-4 h-4 text-yellow-400 shrink-0 mt-0.5" />
          <p className="text-yellow-200/80">
            The ICP network charges a small ledger fee (~0.0001 ICP) per
            transfer. This is standard across all ICP transactions.
          </p>
        </div>
      </div>
    ),
  },
  {
    num: 5,
    icon: <Sparkles className="w-5 h-5" />,
    title: "Play Demo First",
    color: "#f0c040",
    description: "Practice with free virtual credits before betting real ICP",
    content: (
      <div className="space-y-3">
        <p className="text-sm text-muted-foreground">
          Every new player receives{" "}
          <span className="text-yellow-300 font-semibold">
            Demo Credits (DC)
          </span>{" "}
          — free virtual currency for practicing. Demo mode has the exact same
          gameplay, animations, AI Oracle, and Token Soul XP as live mode. No
          real ICP is ever at risk.
        </p>
        <ol className="space-y-2">
          {[
            "Click Play in the navigation",
            "In the Game Lobby, select any game mode",
            'Toggle "Demo Mode" ON before creating/joining a game',
            "Play as many demo games as you like — your DC balance resets when low",
          ].map((step, i) => (
            <li
              // biome-ignore lint/suspicious/noArrayIndexKey: static ordered list
              key={i}
              className="flex items-start gap-2 text-sm text-muted-foreground"
            >
              <span className="text-yellow-400 font-bold shrink-0">
                {i + 1}.
              </span>
              {step}
            </li>
          ))}
        </ol>
        <div className="flex items-start gap-2 p-3 rounded-lg bg-yellow-500/10 border border-yellow-500/20 text-xs">
          <CheckCircle2 className="w-4 h-4 text-yellow-400 shrink-0 mt-0.5" />
          <p className="text-yellow-200/80">
            Your Token Souls still earn XP in Demo mode! Level them up before
            you go live.
          </p>
        </div>
      </div>
    ),
  },
  {
    num: 6,
    icon: <Gamepad2 className="w-5 h-5" />,
    title: "Place a Bet and Play Live",
    color: "#ec4899",
    description: "Wager real ICP from 1 to 1,000,000 per game",
    content: (
      <div className="space-y-3">
        <p className="text-sm text-muted-foreground">
          Once you have ICP in your wallet, you're ready to play for real.
        </p>
        <ol className="space-y-2">
          {[
            "Go to the Game Lobby → choose a game mode (Classic, Quick, Master, or Magic)",
            "Enter your bet amount: 1 ICP minimum, up to 1,000,000 ICP",
            "Create a game room (public or private) or join an existing one",
            "Wait for other players to join (or add AI bots to fill spots)",
            "Roll dice → move tokens → be the first to get all 4 tokens home to WIN",
            "Winner receives 95% of the total pot. Platform fee: 5%",
          ].map((step, i) => (
            <li
              // biome-ignore lint/suspicious/noArrayIndexKey: static ordered list
              key={i}
              className="flex items-start gap-2 text-sm text-muted-foreground"
            >
              <span className="text-pink-400 font-bold shrink-0">{i + 1}.</span>
              {step}
            </li>
          ))}
        </ol>
      </div>
    ),
  },
  {
    num: 7,
    icon: <ArrowUpFromLine className="w-5 h-5" />,
    title: "Withdraw Your Winnings",
    color: "#f97316",
    description: "Cash out to any ICP wallet or exchange anytime",
    content: (
      <div className="space-y-3">
        <p className="text-sm text-muted-foreground">
          Withdraw your ICP balance to any external wallet at any time.
        </p>
        <ol className="space-y-2">
          {[
            "Go to Wallet → Withdraw tab",
            "Enter the destination Principal ID (your exchange deposit address or personal wallet)",
            "Enter the withdrawal amount",
            'Click "Withdraw ICP" and confirm',
            "Funds arrive in 1–2 minutes on the ICP blockchain",
          ].map((step, i) => (
            <li
              // biome-ignore lint/suspicious/noArrayIndexKey: static ordered list
              key={i}
              className="flex items-start gap-2 text-sm text-muted-foreground"
            >
              <span className="text-orange-400 font-bold shrink-0">
                {i + 1}.
              </span>
              {step}
            </li>
          ))}
        </ol>
        <div className="flex items-start gap-2 p-3 rounded-lg bg-rose-500/10 border border-rose-500/20 text-xs">
          <AlertCircle className="w-4 h-4 text-rose-400 shrink-0 mt-0.5" />
          <p className="text-rose-200/80">
            Withdrawals are irreversible. Always double-check the destination
            address before confirming. Blockchain transactions cannot be undone.
          </p>
        </div>
      </div>
    ),
  },
];

function FAQItem({ question, answer }: { question: string; answer: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div
      className="border border-border rounded-xl overflow-hidden"
      data-ocid="guide.faq.item"
    >
      <button
        type="button"
        onClick={() => setOpen((prev) => !prev)}
        className="w-full flex items-center justify-between p-4 text-left hover:bg-white/5 transition-colors"
        data-ocid="guide.faq.toggle"
        aria-expanded={open}
      >
        <span className="text-sm font-semibold text-foreground/90 flex items-center gap-2">
          <HelpCircle className="w-4 h-4 text-purple-400 shrink-0" />
          {question}
        </span>
        <ChevronDown
          className="w-4 h-4 text-muted-foreground shrink-0 transition-transform duration-200"
          style={{ transform: open ? "rotate(180deg)" : "rotate(0deg)" }}
        />
      </button>
      {open && (
        <div className="px-4 pb-4 pt-0">
          <p className="text-sm text-muted-foreground leading-relaxed">
            {answer}
          </p>
        </div>
      )}
    </div>
  );
}

export default function UserGuide({ onNavigate }: UserGuideProps) {
  const { identity } = useInternetIdentity();
  const { data: officialWalletsData } = useGetOfficialWallets();
  const [copied, setCopied] = useState<string | null>(null);
  const depositAddress = identity?.getPrincipal().toString() ?? "";
  const displayedWallets = officialWalletsData?.length
    ? officialWalletsData
    : OFFICIAL_WALLETS;

  const copyText = (text: string, key: string) => {
    navigator.clipboard.writeText(text);
    setCopied(key);
    toast.success("Copied to clipboard!");
    setTimeout(() => setCopied(null), 2000);
  };

  return (
    <div className="space-y-8 max-w-3xl mx-auto" data-ocid="guide.page">
      {/* Header */}
      <div className="text-center space-y-3">
        <Badge className="bg-cyan-500/20 text-cyan-300 border border-cyan-500/30 text-sm px-4 py-1">
          Complete Beginner's Guide
        </Badge>
        <h2
          className="text-4xl font-bold"
          style={{
            background: "linear-gradient(90deg, #22d3ee, #a855f7, #ec4899)",
            WebkitBackgroundClip: "text",
            WebkitTextFillColor: "transparent",
          }}
        >
          Getting Started with LudoVerse ICP
        </h2>
        <p className="text-muted-foreground">
          No crypto experience needed — follow these steps and you're playing in
          minutes
        </p>
      </div>

      {/* Step-by-step */}
      <div className="space-y-4" data-ocid="guide.steps.list">
        {STEPS.map((step) => (
          <Card
            key={step.num}
            className="border-border bg-card overflow-hidden"
            data-ocid={`guide.step.item.${step.num}`}
          >
            <CardHeader className="pb-3">
              <CardTitle className="flex items-center gap-3 text-lg">
                <div
                  className="w-10 h-10 rounded-xl flex items-center justify-center shrink-0 font-bold text-sm"
                  style={{
                    background: `${step.color}20`,
                    border: `1px solid ${step.color}40`,
                    color: step.color,
                  }}
                >
                  {step.num}
                </div>
                <div
                  className="flex items-center gap-2"
                  style={{ color: step.color }}
                >
                  {step.icon}
                </div>
                <div>
                  <p className="text-base font-semibold text-foreground">
                    {step.title}
                  </p>
                  <p className="text-xs text-muted-foreground font-normal mt-0.5">
                    {step.description}
                  </p>
                </div>
              </CardTitle>
            </CardHeader>
            <CardContent className="pt-0">{step.content}</CardContent>
          </Card>
        ))}
      </div>

      {/* Your deposit address (if logged in) */}
      {depositAddress && (
        <Card
          className="border-cyan-500/30 bg-card"
          data-ocid="guide.deposit_address.card"
        >
          <CardHeader className="pb-2">
            <CardTitle className="text-base flex items-center gap-2">
              <Wallet className="w-4 h-4 text-cyan-400" />
              Your Deposit Address
            </CardTitle>
            <CardDescription className="text-xs">
              Copy this Principal ID to receive ICP from any exchange or wallet
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="flex items-start gap-2">
              <code className="flex-1 text-xs font-mono bg-black/30 p-3 rounded-lg break-all text-cyan-300 min-w-0">
                {depositAddress}
              </code>
              <Button
                variant="ghost"
                size="icon"
                onClick={() => copyText(depositAddress, "guide-address")}
                className="text-cyan-400 hover:bg-cyan-500/10 shrink-0"
                aria-label="Copy deposit address"
                data-ocid="guide.copy_address.button"
              >
                {copied === "guide-address" ? (
                  <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                ) : (
                  <Copy className="w-4 h-4" />
                )}
              </Button>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Official Wallets */}
      <Card
        className="border-purple-500/20 bg-card"
        data-ocid="guide.official_wallets.card"
      >
        <CardHeader className="pb-2">
          <CardTitle className="text-base flex items-center gap-2">
            <Shield className="w-4 h-4 text-purple-400" />
            Official LudoVerse Platform Wallets
          </CardTitle>
          <CardDescription className="text-xs">
            All platform fees (5% of each game pot) are collected to these
            verified wallets
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-2">
          {displayedWallets.map((w, i) => (
            <div
              key={w.address}
              className="flex items-center gap-3 rounded-lg border border-purple-500/20 p-3"
              style={{ background: "rgba(168,85,247,0.05)" }}
              data-ocid={`guide.official_wallet.item.${i + 1}`}
            >
              <div className="flex-1 min-w-0">
                <p className="text-xs font-semibold text-purple-300 mb-0.5">
                  {w.walletLabel}
                </p>
                <code className="text-[10px] font-mono text-muted-foreground break-all">
                  {w.address}
                </code>
              </div>
              <Button
                variant="ghost"
                size="icon"
                onClick={() => copyText(w.address, `guide-wallet-${i}`)}
                className="text-purple-400 hover:bg-purple-500/10 shrink-0"
                aria-label="Copy wallet address"
                data-ocid={`guide.copy_wallet.button.${i + 1}`}
              >
                {copied === `guide-wallet-${i}` ? (
                  <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                ) : (
                  <Copy className="w-4 h-4" />
                )}
              </Button>
            </div>
          ))}
        </CardContent>
      </Card>

      {/* FAQ */}
      <div data-ocid="guide.faq.section">
        <h3 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-2">
          <HelpCircle className="w-6 h-6 text-purple-400" />
          Frequently Asked Questions
        </h3>
        <div className="space-y-2">
          {FAQS.map((faq) => (
            <FAQItem key={faq.q} question={faq.q} answer={faq.a} />
          ))}
        </div>
      </div>

      {/* CTA buttons */}
      {onNavigate && (
        <div
          className="flex flex-col sm:flex-row gap-3"
          data-ocid="guide.cta.section"
        >
          <Button
            onClick={() => onNavigate("wallet")}
            className="flex-1 font-semibold gap-2"
            style={{ background: "linear-gradient(90deg, #22d3ee, #a855f7)" }}
            size="lg"
            data-ocid="guide.go_wallet.button"
          >
            <Wallet className="w-4 h-4" />
            Go to Wallet
          </Button>
          <Button
            onClick={() => onNavigate("lobby")}
            variant="outline"
            className="flex-1 font-semibold gap-2 border-pink-500/30 text-pink-300 hover:bg-pink-500/10"
            size="lg"
            data-ocid="guide.go_lobby.button"
          >
            <Gamepad2 className="w-4 h-4" />
            Play Now
          </Button>
        </div>
      )}

      {/* External resources */}
      <Card className="border-border bg-card" data-ocid="guide.resources.card">
        <CardHeader className="pb-2">
          <CardTitle className="text-base flex items-center gap-2">
            <ExternalLink className="w-4 h-4 text-blue-400" />
            Learn More About ICP
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-2">
          {[
            {
              label: "Internet Computer Official Website",
              url: "https://internetcomputer.org",
            },
            {
              label: "Internet Identity Portal",
              url: "https://identity.ic0.app",
            },
            {
              label: "ICP Token Overview",
              url: "https://internetcomputer.org/icp",
            },
          ].map((link) => (
            <a
              key={link.url}
              href={link.url}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-2 text-sm text-blue-400 hover:text-blue-300 transition-colors p-1"
            >
              <ExternalLink className="w-3 h-3 shrink-0" />
              {link.label}
            </a>
          ))}
        </CardContent>
      </Card>
    </div>
  );
}
