/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Wallet = IDL.Record({
  'id' : IDL.Principal,
  'balance' : IDL.Float64,
  'createdAt' : IDL.Int,
  'demoCredits' : IDL.Float64,
  'lastActive' : IDL.Int,
});
export const GameMode = IDL.Variant({
  'magic' : IDL.Null,
  'timed' : IDL.Null,
  'challenge' : IDL.Null,
  'advanced' : IDL.Null,
  'experimental' : IDL.Null,
  'custom' : IDL.Null,
  'demo' : IDL.Null,
  'team' : IDL.Null,
  'superLudo' : IDL.Null,
  'quick' : IDL.Null,
  'tournament' : IDL.Null,
  'classic' : IDL.Null,
  'twoVsTwo' : IDL.Null,
  'practice' : IDL.Null,
  'bonus' : IDL.Null,
  'master' : IDL.Null,
  'copyClassic' : IDL.Null,
  'copyFast' : IDL.Null,
});
export const RoomType = IDL.Variant({
  'privateRoom' : IDL.Null,
  'isPublic' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'referralCode' : IDL.Text,
  'gamesPlayed' : IDL.Float64,
  'isPremium' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'color' : IDL.Text,
  'wins' : IDL.Float64,
  'losses' : IDL.Float64,
  'icpBalance' : IDL.Float64,
  'currentGame' : IDL.Opt(IDL.Principal),
  'avatarUrl' : IDL.Text,
  'demoCredits' : IDL.Float64,
  'draws' : IDL.Float64,
  'lastActive' : IDL.Int,
});
export const BotDifficulty = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'medium' : IDL.Null,
});
export const BotConfig = IDL.Record({
  'principal' : IDL.Principal,
  'balance' : IDL.Float64,
  'isPremium' : IDL.Bool,
  'difficulty' : BotDifficulty,
  'name' : IDL.Text,
});
export const TokenPosition = IDL.Record({
  'isFinished' : IDL.Bool,
  'tokenIndex' : IDL.Nat,
  'isHome' : IDL.Bool,
  'isSafe' : IDL.Bool,
  'position' : IDL.Int,
});
export const PlayerState = IDL.Record({
  'principal' : IDL.Principal,
  'lastBetAmount' : IDL.Float64,
  'tokens' : IDL.Vec(TokenPosition),
  'consecutiveWins' : IDL.Nat,
});
export const GameStatus = IDL.Variant({
  'active' : IDL.Null,
  'completed' : IDL.Null,
  'waiting' : IDL.Null,
});
export const DiceRoll = IDL.Record({
  'seedHash' : IDL.Text,
  'seed' : IDL.Text,
  'diceResult' : IDL.Nat,
  'entropy' : IDL.Text,
  'rollNumber' : IDL.Nat,
  'timestamp' : IDL.Int,
  'playerPrincipal' : IDL.Principal,
});
export const RankedStatus = IDL.Variant({
  'ranked' : IDL.Null,
  'unranked' : IDL.Null,
});
export const GameSession = IDL.Record({
  'id' : IDL.Principal,
  'playerStates' : IDL.Vec(PlayerState),
  'status' : GameStatus,
  'betAmount' : IDL.Float64,
  'mode' : GameMode,
  'createdAt' : IDL.Int,
  'winner' : IDL.Opt(IDL.Principal),
  'isDemo' : IDL.Bool,
  'currentTurn' : IDL.Nat,
  'players' : IDL.Vec(IDL.Principal),
  'diceHistory' : IDL.Vec(DiceRoll),
  'rankedStatus' : RankedStatus,
});
export const MatchmakingRoom = IDL.Record({
  'id' : IDL.Principal,
  'status' : IDL.Variant({
    'active' : IDL.Null,
    'completed' : IDL.Null,
    'waiting' : IDL.Null,
  }),
  'creator' : IDL.Principal,
  'betAmount' : IDL.Float64,
  'createdAt' : IDL.Int,
  'playerCount' : IDL.Nat,
  'isDemo' : IDL.Bool,
  'players' : IDL.Vec(IDL.Principal),
  'gameMode' : GameMode,
  'roomType' : RoomType,
  'maxPlayers' : IDL.Nat,
});
export const BoardState = IDL.Record({
  'betMultiplier' : IDL.Float64,
  'winStreakPlayer' : IDL.Opt(IDL.Principal),
  'state' : IDL.Text,
  'glowIntensity' : IDL.Float64,
});
export const FeaturedGame = IDL.Record({
  'status' : GameStatus,
  'betAmount' : IDL.Float64,
  'spectatorCount' : IDL.Nat,
  'mode' : GameMode,
  'gameId' : IDL.Principal,
  'playerCount' : IDL.Nat,
});
export const MoveProbability = IDL.Record({
  'probability' : IDL.Float64,
  'safeScore' : IDL.Float64,
  'captureChance' : IDL.Float64,
  'position' : IDL.Int,
});
export const OfficialWallet = IDL.Record({
  'address' : IDL.Text,
  'walletLabel' : IDL.Text,
});
export const SpectatorReaction = IDL.Record({
  'reactorPrincipal' : IDL.Principal,
  'emoji' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const SystemStats = IDL.Record({
  'totalPlayers' : IDL.Nat,
  'totalGames' : IDL.Nat,
  'totalSpectators' : IDL.Nat,
  'totalBetsVolume' : IDL.Float64,
  'activeGames' : IDL.Nat,
});
export const TokenSoul = IDL.Record({
  'xp' : IDL.Nat,
  'tokenIndex' : IDL.Nat,
  'level' : IDL.Nat,
  'capturedCount' : IDL.Nat,
  'nearMissCount' : IDL.Nat,
  'captureCount' : IDL.Nat,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'txType' : IDL.Variant({
    'withdraw' : IDL.Null,
    'betLock' : IDL.Null,
    'betRefund' : IDL.Null,
    'deposit' : IDL.Null,
    'betWin' : IDL.Null,
  }),
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addTokenXP' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'automaticUserInitialization' : IDL.Func(
      [],
      [
        IDL.Record({
          'loginSuccess' : IDL.Bool,
          'message' : IDL.Text,
          'wallet' : Wallet,
          'playerExists' : IDL.Bool,
        }),
      ],
      [],
    ),
  'createGame' : IDL.Func(
      [GameMode, IDL.Float64, IDL.Bool],
      [IDL.Principal],
      [],
    ),
  'createMatchmakingRoom' : IDL.Func(
      [RoomType, GameMode, IDL.Float64, IDL.Nat, IDL.Bool],
      [IDL.Principal],
      [],
    ),
  'createUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deposit' : IDL.Func([IDL.Float64], [IDL.Bool], []),
  'forfeitGame' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'generateReferralLink' : IDL.Func([], [IDL.Text], ['query']),
  'getAllPlayers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAvailableBots' : IDL.Func([], [IDL.Vec(BotConfig)], ['query']),
  'getAvailableGames' : IDL.Func([], [IDL.Vec(GameSession)], ['query']),
  'getAvailableRooms' : IDL.Func([], [IDL.Vec(MatchmakingRoom)], ['query']),
  'getBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getBoardState' : IDL.Func([IDL.Principal], [BoardState], ['query']),
  'getBotMove' : IDL.Func([IDL.Principal, IDL.Principal], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getDemoCredits' : IDL.Func([], [IDL.Float64], ['query']),
  'getFeaturedGames' : IDL.Func([], [IDL.Vec(FeaturedGame)], ['query']),
  'getGame' : IDL.Func([IDL.Principal], [IDL.Opt(GameSession)], ['query']),
  'getMoveProbabilities' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(MoveProbability)],
      ['query'],
    ),
  'getOfficialWallets' : IDL.Func([], [IDL.Vec(OfficialWallet)], ['query']),
  'getRoomState' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(MatchmakingRoom)],
      ['query'],
    ),
  'getSpectatorCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getSpectatorReactions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(SpectatorReaction)],
      ['query'],
    ),
  'getSystemStats' : IDL.Func([], [SystemStats], ['query']),
  'getTokenSouls' : IDL.Func([IDL.Principal], [IDL.Vec(TokenSoul)], ['query']),
  'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWallet' : IDL.Func([], [IDL.Opt(Wallet)], ['query']),
  'getWinner' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Principal)], ['query']),
  'isFirstTime' : IDL.Func([], [IDL.Bool], ['query']),
  'isPremium' : IDL.Func([], [IDL.Bool], ['query']),
  'joinAsSpectator' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'joinGame' : IDL.Func([IDL.Principal, IDL.Bool], [IDL.Bool], []),
  'joinRoom' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'leaveRoom' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'leaveSpectator' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'moveToken' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Nat], [GameSession], []),
  'registerBot' : IDL.Func([IDL.Text, BotDifficulty], [IDL.Principal], []),
  'resetDemoCredits' : IDL.Func([], [IDL.Float64], []),
  'rollDice' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Record({
          'valid' : IDL.Bool,
          'value' : IDL.Nat,
          'seedHash' : IDL.Text,
          'entropy' : IDL.Text,
        }),
      ],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'sendSpectatorReaction' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Bool], []),
  'updatePlayer' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'upgradeToPremium' : IDL.Func([], [IDL.Bool], []),
  'withdraw' : IDL.Func([IDL.Float64], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Wallet = IDL.Record({
    'id' : IDL.Principal,
    'balance' : IDL.Float64,
    'createdAt' : IDL.Int,
    'demoCredits' : IDL.Float64,
    'lastActive' : IDL.Int,
  });
  const GameMode = IDL.Variant({
    'magic' : IDL.Null,
    'timed' : IDL.Null,
    'challenge' : IDL.Null,
    'advanced' : IDL.Null,
    'experimental' : IDL.Null,
    'custom' : IDL.Null,
    'demo' : IDL.Null,
    'team' : IDL.Null,
    'superLudo' : IDL.Null,
    'quick' : IDL.Null,
    'tournament' : IDL.Null,
    'classic' : IDL.Null,
    'twoVsTwo' : IDL.Null,
    'practice' : IDL.Null,
    'bonus' : IDL.Null,
    'master' : IDL.Null,
    'copyClassic' : IDL.Null,
    'copyFast' : IDL.Null,
  });
  const RoomType = IDL.Variant({
    'privateRoom' : IDL.Null,
    'isPublic' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'referralCode' : IDL.Text,
    'gamesPlayed' : IDL.Float64,
    'isPremium' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'color' : IDL.Text,
    'wins' : IDL.Float64,
    'losses' : IDL.Float64,
    'icpBalance' : IDL.Float64,
    'currentGame' : IDL.Opt(IDL.Principal),
    'avatarUrl' : IDL.Text,
    'demoCredits' : IDL.Float64,
    'draws' : IDL.Float64,
    'lastActive' : IDL.Int,
  });
  const BotDifficulty = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  });
  const BotConfig = IDL.Record({
    'principal' : IDL.Principal,
    'balance' : IDL.Float64,
    'isPremium' : IDL.Bool,
    'difficulty' : BotDifficulty,
    'name' : IDL.Text,
  });
  const TokenPosition = IDL.Record({
    'isFinished' : IDL.Bool,
    'tokenIndex' : IDL.Nat,
    'isHome' : IDL.Bool,
    'isSafe' : IDL.Bool,
    'position' : IDL.Int,
  });
  const PlayerState = IDL.Record({
    'principal' : IDL.Principal,
    'lastBetAmount' : IDL.Float64,
    'tokens' : IDL.Vec(TokenPosition),
    'consecutiveWins' : IDL.Nat,
  });
  const GameStatus = IDL.Variant({
    'active' : IDL.Null,
    'completed' : IDL.Null,
    'waiting' : IDL.Null,
  });
  const DiceRoll = IDL.Record({
    'seedHash' : IDL.Text,
    'seed' : IDL.Text,
    'diceResult' : IDL.Nat,
    'entropy' : IDL.Text,
    'rollNumber' : IDL.Nat,
    'timestamp' : IDL.Int,
    'playerPrincipal' : IDL.Principal,
  });
  const RankedStatus = IDL.Variant({
    'ranked' : IDL.Null,
    'unranked' : IDL.Null,
  });
  const GameSession = IDL.Record({
    'id' : IDL.Principal,
    'playerStates' : IDL.Vec(PlayerState),
    'status' : GameStatus,
    'betAmount' : IDL.Float64,
    'mode' : GameMode,
    'createdAt' : IDL.Int,
    'winner' : IDL.Opt(IDL.Principal),
    'isDemo' : IDL.Bool,
    'currentTurn' : IDL.Nat,
    'players' : IDL.Vec(IDL.Principal),
    'diceHistory' : IDL.Vec(DiceRoll),
    'rankedStatus' : RankedStatus,
  });
  const MatchmakingRoom = IDL.Record({
    'id' : IDL.Principal,
    'status' : IDL.Variant({
      'active' : IDL.Null,
      'completed' : IDL.Null,
      'waiting' : IDL.Null,
    }),
    'creator' : IDL.Principal,
    'betAmount' : IDL.Float64,
    'createdAt' : IDL.Int,
    'playerCount' : IDL.Nat,
    'isDemo' : IDL.Bool,
    'players' : IDL.Vec(IDL.Principal),
    'gameMode' : GameMode,
    'roomType' : RoomType,
    'maxPlayers' : IDL.Nat,
  });
  const BoardState = IDL.Record({
    'betMultiplier' : IDL.Float64,
    'winStreakPlayer' : IDL.Opt(IDL.Principal),
    'state' : IDL.Text,
    'glowIntensity' : IDL.Float64,
  });
  const FeaturedGame = IDL.Record({
    'status' : GameStatus,
    'betAmount' : IDL.Float64,
    'spectatorCount' : IDL.Nat,
    'mode' : GameMode,
    'gameId' : IDL.Principal,
    'playerCount' : IDL.Nat,
  });
  const MoveProbability = IDL.Record({
    'probability' : IDL.Float64,
    'safeScore' : IDL.Float64,
    'captureChance' : IDL.Float64,
    'position' : IDL.Int,
  });
  const OfficialWallet = IDL.Record({
    'address' : IDL.Text,
    'walletLabel' : IDL.Text,
  });
  const SpectatorReaction = IDL.Record({
    'reactorPrincipal' : IDL.Principal,
    'emoji' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const SystemStats = IDL.Record({
    'totalPlayers' : IDL.Nat,
    'totalGames' : IDL.Nat,
    'totalSpectators' : IDL.Nat,
    'totalBetsVolume' : IDL.Float64,
    'activeGames' : IDL.Nat,
  });
  const TokenSoul = IDL.Record({
    'xp' : IDL.Nat,
    'tokenIndex' : IDL.Nat,
    'level' : IDL.Nat,
    'capturedCount' : IDL.Nat,
    'nearMissCount' : IDL.Nat,
    'captureCount' : IDL.Nat,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'txType' : IDL.Variant({
      'withdraw' : IDL.Null,
      'betLock' : IDL.Null,
      'betRefund' : IDL.Null,
      'deposit' : IDL.Null,
      'betWin' : IDL.Null,
    }),
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    'addTokenXP' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'automaticUserInitialization' : IDL.Func(
        [],
        [
          IDL.Record({
            'loginSuccess' : IDL.Bool,
            'message' : IDL.Text,
            'wallet' : Wallet,
            'playerExists' : IDL.Bool,
          }),
        ],
        [],
      ),
    'createGame' : IDL.Func(
        [GameMode, IDL.Float64, IDL.Bool],
        [IDL.Principal],
        [],
      ),
    'createMatchmakingRoom' : IDL.Func(
        [RoomType, GameMode, IDL.Float64, IDL.Nat, IDL.Bool],
        [IDL.Principal],
        [],
      ),
    'createUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deposit' : IDL.Func([IDL.Float64], [IDL.Bool], []),
    'forfeitGame' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'generateReferralLink' : IDL.Func([], [IDL.Text], ['query']),
    'getAllPlayers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAvailableBots' : IDL.Func([], [IDL.Vec(BotConfig)], ['query']),
    'getAvailableGames' : IDL.Func([], [IDL.Vec(GameSession)], ['query']),
    'getAvailableRooms' : IDL.Func([], [IDL.Vec(MatchmakingRoom)], ['query']),
    'getBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getBoardState' : IDL.Func([IDL.Principal], [BoardState], ['query']),
    'getBotMove' : IDL.Func(
        [IDL.Principal, IDL.Principal],
        [IDL.Nat],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getDemoCredits' : IDL.Func([], [IDL.Float64], ['query']),
    'getFeaturedGames' : IDL.Func([], [IDL.Vec(FeaturedGame)], ['query']),
    'getGame' : IDL.Func([IDL.Principal], [IDL.Opt(GameSession)], ['query']),
    'getMoveProbabilities' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(MoveProbability)],
        ['query'],
      ),
    'getOfficialWallets' : IDL.Func([], [IDL.Vec(OfficialWallet)], ['query']),
    'getRoomState' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(MatchmakingRoom)],
        ['query'],
      ),
    'getSpectatorCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getSpectatorReactions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(SpectatorReaction)],
        ['query'],
      ),
    'getSystemStats' : IDL.Func([], [SystemStats], ['query']),
    'getTokenSouls' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(TokenSoul)],
        ['query'],
      ),
    'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWallet' : IDL.Func([], [IDL.Opt(Wallet)], ['query']),
    'getWinner' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Principal)],
        ['query'],
      ),
    'isFirstTime' : IDL.Func([], [IDL.Bool], ['query']),
    'isPremium' : IDL.Func([], [IDL.Bool], ['query']),
    'joinAsSpectator' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'joinGame' : IDL.Func([IDL.Principal, IDL.Bool], [IDL.Bool], []),
    'joinRoom' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'leaveRoom' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'leaveSpectator' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'moveToken' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Nat],
        [GameSession],
        [],
      ),
    'registerBot' : IDL.Func([IDL.Text, BotDifficulty], [IDL.Principal], []),
    'resetDemoCredits' : IDL.Func([], [IDL.Float64], []),
    'rollDice' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Record({
            'valid' : IDL.Bool,
            'value' : IDL.Nat,
            'seedHash' : IDL.Text,
            'entropy' : IDL.Text,
          }),
        ],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'sendSpectatorReaction' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updatePlayer' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'upgradeToPremium' : IDL.Func([], [IDL.Bool], []),
    'withdraw' : IDL.Func([IDL.Float64], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };