/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BoardState {
  'betMultiplier' : number,
  'winStreakPlayer' : [] | [Principal],
  'state' : string,
  'glowIntensity' : number,
}
export interface BotConfig {
  'principal' : Principal,
  'balance' : number,
  'isPremium' : boolean,
  'difficulty' : BotDifficulty,
  'name' : string,
}
export type BotDifficulty = { 'easy' : null } |
  { 'hard' : null } |
  { 'medium' : null };
export interface DiceRoll {
  'seedHash' : string,
  'seed' : string,
  'diceResult' : bigint,
  'entropy' : string,
  'rollNumber' : bigint,
  'timestamp' : bigint,
  'playerPrincipal' : Principal,
}
export interface FeaturedGame {
  'status' : GameStatus,
  'betAmount' : number,
  'spectatorCount' : bigint,
  'mode' : GameMode,
  'gameId' : Principal,
  'playerCount' : bigint,
}
export type GameMode = { 'magic' : null } |
  { 'timed' : null } |
  { 'challenge' : null } |
  { 'advanced' : null } |
  { 'experimental' : null } |
  { 'custom' : null } |
  { 'demo' : null } |
  { 'team' : null } |
  { 'superLudo' : null } |
  { 'quick' : null } |
  { 'tournament' : null } |
  { 'classic' : null } |
  { 'twoVsTwo' : null } |
  { 'practice' : null } |
  { 'bonus' : null } |
  { 'master' : null } |
  { 'copyClassic' : null } |
  { 'copyFast' : null };
export interface GameSession {
  'id' : Principal,
  'playerStates' : Array<PlayerState>,
  'status' : GameStatus,
  'betAmount' : number,
  'mode' : GameMode,
  'createdAt' : bigint,
  'winner' : [] | [Principal],
  'isDemo' : boolean,
  'currentTurn' : bigint,
  'players' : Array<Principal>,
  'diceHistory' : Array<DiceRoll>,
  'rankedStatus' : RankedStatus,
}
export type GameStatus = { 'active' : null } |
  { 'completed' : null } |
  { 'waiting' : null };
export interface MatchmakingRoom {
  'id' : Principal,
  'status' : { 'active' : null } |
    { 'completed' : null } |
    { 'waiting' : null },
  'creator' : Principal,
  'betAmount' : number,
  'createdAt' : bigint,
  'playerCount' : bigint,
  'isDemo' : boolean,
  'players' : Array<Principal>,
  'gameMode' : GameMode,
  'roomType' : RoomType,
  'maxPlayers' : bigint,
}
export interface MoveProbability {
  'probability' : number,
  'safeScore' : number,
  'captureChance' : number,
  'position' : bigint,
}
export interface OfficialWallet { 'address' : string, 'walletLabel' : string }
export interface PlayerState {
  'principal' : Principal,
  'lastBetAmount' : number,
  'tokens' : Array<TokenPosition>,
  'consecutiveWins' : bigint,
}
export type RankedStatus = { 'ranked' : null } |
  { 'unranked' : null };
export type RoomType = { 'privateRoom' : null } |
  { 'isPublic' : null };
export interface SpectatorReaction {
  'reactorPrincipal' : Principal,
  'emoji' : string,
  'timestamp' : bigint,
}
export interface SystemStats {
  'totalPlayers' : bigint,
  'totalGames' : bigint,
  'totalSpectators' : bigint,
  'totalBetsVolume' : number,
  'activeGames' : bigint,
}
export interface TokenPosition {
  'isFinished' : boolean,
  'tokenIndex' : bigint,
  'isHome' : boolean,
  'isSafe' : boolean,
  'position' : bigint,
}
export interface TokenSoul {
  'xp' : bigint,
  'tokenIndex' : bigint,
  'level' : bigint,
  'capturedCount' : bigint,
  'nearMissCount' : bigint,
  'captureCount' : bigint,
}
export interface Transaction {
  'id' : bigint,
  'description' : string,
  'timestamp' : bigint,
  'txType' : { 'withdraw' : null } |
    { 'betLock' : null } |
    { 'betRefund' : null } |
    { 'deposit' : null } |
    { 'betWin' : null },
  'amount' : number,
}
export interface UserProfile {
  'bio' : string,
  'referralCode' : string,
  'gamesPlayed' : number,
  'isPremium' : boolean,
  'name' : string,
  'createdAt' : bigint,
  'color' : string,
  'wins' : number,
  'losses' : number,
  'icpBalance' : number,
  'currentGame' : [] | [Principal],
  'avatarUrl' : string,
  'demoCredits' : number,
  'draws' : number,
  'lastActive' : bigint,
}
export interface Wallet {
  'id' : Principal,
  'balance' : number,
  'createdAt' : bigint,
  'demoCredits' : number,
  'lastActive' : bigint,
}
export interface _SERVICE {
  'addTokenXP' : ActorMethod<[bigint, bigint], undefined>,
  'automaticUserInitialization' : ActorMethod<
    [],
    {
      'loginSuccess' : boolean,
      'message' : string,
      'wallet' : Wallet,
      'playerExists' : boolean,
    }
  >,
  'createGame' : ActorMethod<[GameMode, number, boolean], Principal>,
  'createMatchmakingRoom' : ActorMethod<
    [RoomType, GameMode, number, bigint, boolean],
    Principal
  >,
  'createUser' : ActorMethod<[string, string], undefined>,
  'deposit' : ActorMethod<[number], boolean>,
  'forfeitGame' : ActorMethod<[Principal], boolean>,
  'generateReferralLink' : ActorMethod<[], string>,
  'getAllPlayers' : ActorMethod<[], Array<UserProfile>>,
  'getAvailableBots' : ActorMethod<[], Array<BotConfig>>,
  'getAvailableGames' : ActorMethod<[], Array<GameSession>>,
  'getAvailableRooms' : ActorMethod<[], Array<MatchmakingRoom>>,
  'getBalance' : ActorMethod<[], number>,
  'getBoardState' : ActorMethod<[Principal], BoardState>,
  'getBotMove' : ActorMethod<[Principal, Principal], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getDemoCredits' : ActorMethod<[], number>,
  'getFeaturedGames' : ActorMethod<[], Array<FeaturedGame>>,
  'getGame' : ActorMethod<[Principal], [] | [GameSession]>,
  'getMoveProbabilities' : ActorMethod<[Principal], Array<MoveProbability>>,
  'getOfficialWallets' : ActorMethod<[], Array<OfficialWallet>>,
  'getRoomState' : ActorMethod<[Principal], [] | [MatchmakingRoom]>,
  'getSpectatorCount' : ActorMethod<[Principal], bigint>,
  'getSpectatorReactions' : ActorMethod<[Principal], Array<SpectatorReaction>>,
  'getSystemStats' : ActorMethod<[], SystemStats>,
  'getTokenSouls' : ActorMethod<[Principal], Array<TokenSoul>>,
  'getTransactionHistory' : ActorMethod<[], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWallet' : ActorMethod<[], [] | [Wallet]>,
  'getWinner' : ActorMethod<[Principal], [] | [Principal]>,
  'isFirstTime' : ActorMethod<[], boolean>,
  'isPremium' : ActorMethod<[], boolean>,
  'joinAsSpectator' : ActorMethod<[Principal], boolean>,
  'joinGame' : ActorMethod<[Principal, boolean], boolean>,
  'joinRoom' : ActorMethod<[Principal], boolean>,
  'leaveRoom' : ActorMethod<[Principal], boolean>,
  'leaveSpectator' : ActorMethod<[Principal], boolean>,
  'moveToken' : ActorMethod<[Principal, bigint, bigint], GameSession>,
  'registerBot' : ActorMethod<[string, BotDifficulty], Principal>,
  'resetDemoCredits' : ActorMethod<[], number>,
  'rollDice' : ActorMethod<
    [Principal],
    {
      'valid' : boolean,
      'value' : bigint,
      'seedHash' : string,
      'entropy' : string,
    }
  >,
  'saveCallerUserProfile' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'sendSpectatorReaction' : ActorMethod<[Principal, string], boolean>,
  'updatePlayer' : ActorMethod<[string, string], undefined>,
  'upgradeToPremium' : ActorMethod<[], boolean>,
  'withdraw' : ActorMethod<[number], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];