/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BotConfig {
    principal: Principal;
    balance: number;
    isPremium: boolean;
    difficulty: BotDifficulty;
    name: string;
}
export interface TokenSoul {
    xp: bigint;
    tokenIndex: bigint;
    level: bigint;
    capturedCount: bigint;
    nearMissCount: bigint;
    captureCount: bigint;
}
export interface TokenPosition {
    isFinished: boolean;
    tokenIndex: bigint;
    isHome: boolean;
    isSafe: boolean;
    position: bigint;
}
export interface SystemStats {
    totalPlayers: bigint;
    totalGames: bigint;
    totalSpectators: bigint;
    totalBetsVolume: number;
    activeGames: bigint;
}
export interface BoardState {
    betMultiplier: number;
    winStreakPlayer?: Principal;
    state: string;
    glowIntensity: number;
}
export interface FeaturedGame {
    status: GameStatus;
    betAmount: number;
    spectatorCount: bigint;
    mode: GameMode;
    gameId: Principal;
    playerCount: bigint;
}
export interface Transaction {
    id: bigint;
    description: string;
    timestamp: bigint;
    txType: Variant_withdraw_betLock_betRefund_deposit_betWin;
    amount: number;
}
export interface Wallet {
    id: Principal;
    balance: number;
    createdAt: bigint;
    demoCredits: number;
    lastActive: bigint;
}
export interface MoveProbability {
    probability: number;
    safeScore: number;
    captureChance: number;
    position: bigint;
}
export interface DiceRoll {
    seedHash: string;
    seed: string;
    diceResult: bigint;
    entropy: string;
    rollNumber: bigint;
    timestamp: bigint;
    playerPrincipal: Principal;
}
export interface SpectatorReaction {
    reactorPrincipal: Principal;
    emoji: string;
    timestamp: bigint;
}
export interface PlayerState {
    principal: Principal;
    lastBetAmount: number;
    tokens: Array<TokenPosition>;
    consecutiveWins: bigint;
}
export interface MatchmakingRoom {
    id: Principal;
    status: GameStatus;
    creator: Principal;
    betAmount: number;
    createdAt: bigint;
    playerCount: bigint;
    isDemo: boolean;
    players: Array<Principal>;
    gameMode: GameMode;
    roomType: RoomType;
    maxPlayers: bigint;
}
export interface OfficialWallet {
    address: string;
    walletLabel: string;
}
export interface UserProfile {
    bio: string;
    referralCode: string;
    gamesPlayed: number;
    isPremium: boolean;
    name: string;
    createdAt: bigint;
    color: string;
    wins: number;
    losses: number;
    icpBalance: number;
    currentGame?: Principal;
    avatarUrl: string;
    demoCredits: number;
    draws: number;
    lastActive: bigint;
}
export interface GameSession {
    id: Principal;
    playerStates: Array<PlayerState>;
    status: GameStatus;
    betAmount: number;
    mode: GameMode;
    createdAt: bigint;
    winner?: Principal;
    isDemo: boolean;
    currentTurn: bigint;
    players: Array<Principal>;
    diceHistory: Array<DiceRoll>;
    rankedStatus: RankedStatus;
}
export enum BotDifficulty {
    easy = "easy",
    hard = "hard",
    medium = "medium"
}
export enum GameMode {
    magic = "magic",
    timed = "timed",
    challenge = "challenge",
    advanced = "advanced",
    experimental = "experimental",
    custom = "custom",
    demo = "demo",
    team = "team",
    superLudo = "superLudo",
    quick = "quick",
    tournament = "tournament",
    classic = "classic",
    twoVsTwo = "twoVsTwo",
    practice = "practice",
    bonus = "bonus",
    master = "master",
    copyClassic = "copyClassic",
    copyFast = "copyFast"
}
export enum GameStatus {
    active = "active",
    completed = "completed",
    waiting = "waiting"
}
export enum RankedStatus {
    ranked = "ranked",
    unranked = "unranked"
}
export enum RoomType {
    privateRoom = "privateRoom",
    isPublic = "isPublic"
}
export enum Variant_withdraw_betLock_betRefund_deposit_betWin {
    withdraw = "withdraw",
    betLock = "betLock",
    betRefund = "betRefund",
    deposit = "deposit",
    betWin = "betWin"
}
export interface backendInterface {
    addTokenXP(tokenIndex: bigint, xp: bigint): Promise<void>;
    automaticUserInitialization(): Promise<{
        loginSuccess: boolean;
        message: string;
        wallet: Wallet;
        playerExists: boolean;
    }>;
    createGame(mode: GameMode, betAmount: number, isDemo: boolean): Promise<Principal>;
    createMatchmakingRoom(roomType: RoomType, gameMode: GameMode, betAmount: number, maxPlayers: bigint, isDemo: boolean): Promise<Principal>;
    createUser(name: string, color: string): Promise<void>;
    deposit(amount: number): Promise<boolean>;
    forfeitGame(gameId: Principal): Promise<boolean>;
    generateReferralLink(): Promise<string>;
    getAllPlayers(): Promise<Array<UserProfile>>;
    getAvailableBots(): Promise<Array<BotConfig>>;
    getAvailableGames(): Promise<Array<GameSession>>;
    getAvailableRooms(): Promise<Array<MatchmakingRoom>>;
    getBalance(): Promise<number>;
    getBoardState(gameId: Principal): Promise<BoardState>;
    getBotMove(gameId: Principal, botPrincipal: Principal): Promise<bigint>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getDemoCredits(): Promise<number>;
    getFeaturedGames(): Promise<Array<FeaturedGame>>;
    getGame(gameId: Principal): Promise<GameSession | null>;
    getMoveProbabilities(gameId: Principal): Promise<Array<MoveProbability>>;
    getOfficialWallets(): Promise<Array<OfficialWallet>>;
    getRoomState(roomId: Principal): Promise<MatchmakingRoom | null>;
    getSpectatorCount(gameId: Principal): Promise<bigint>;
    getSpectatorReactions(gameId: Principal): Promise<Array<SpectatorReaction>>;
    getSystemStats(): Promise<SystemStats>;
    getTokenSouls(player: Principal): Promise<Array<TokenSoul>>;
    getTransactionHistory(): Promise<Array<Transaction>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWallet(): Promise<Wallet | null>;
    getWinner(gameId: Principal): Promise<Principal | null>;
    isFirstTime(): Promise<boolean>;
    isPremium(): Promise<boolean>;
    joinAsSpectator(gameId: Principal): Promise<boolean>;
    joinGame(gameId: Principal, isDemo: boolean): Promise<boolean>;
    joinRoom(roomId: Principal): Promise<boolean>;
    leaveRoom(roomId: Principal): Promise<boolean>;
    leaveSpectator(gameId: Principal): Promise<boolean>;
    moveToken(gameId: Principal, tokenIndex: bigint, rollValue: bigint): Promise<GameSession>;
    registerBot(name: string, difficulty: BotDifficulty): Promise<Principal>;
    resetDemoCredits(): Promise<number>;
    rollDice(gameId: Principal): Promise<{
        valid: boolean;
        value: bigint;
        seedHash: string;
        entropy: string;
    }>;
    saveCallerUserProfile(name: string, color: string, avatarUrl: string, bio: string): Promise<void>;
    sendSpectatorReaction(gameId: Principal, emoji: string): Promise<boolean>;
    updatePlayer(name: string, color: string): Promise<void>;
    upgradeToPremium(): Promise<boolean>;
    withdraw(amount: number): Promise<boolean>;
}
import type { BoardState as _BoardState, BotConfig as _BotConfig, BotDifficulty as _BotDifficulty, DiceRoll as _DiceRoll, FeaturedGame as _FeaturedGame, GameMode as _GameMode, GameSession as _GameSession, GameStatus as _GameStatus, MatchmakingRoom as _MatchmakingRoom, PlayerState as _PlayerState, RankedStatus as _RankedStatus, RoomType as _RoomType, Transaction as _Transaction, UserProfile as _UserProfile, Wallet as _Wallet } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addTokenXP(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTokenXP(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTokenXP(arg0, arg1);
            return result;
        }
    }
    async automaticUserInitialization(): Promise<{
        loginSuccess: boolean;
        message: string;
        wallet: Wallet;
        playerExists: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.automaticUserInitialization();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.automaticUserInitialization();
            return result;
        }
    }
    async createGame(arg0: GameMode, arg1: number, arg2: boolean): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.createGame(to_candid_GameMode_n1(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGame(to_candid_GameMode_n1(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async createMatchmakingRoom(arg0: RoomType, arg1: GameMode, arg2: number, arg3: bigint, arg4: boolean): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.createMatchmakingRoom(to_candid_RoomType_n3(this._uploadFile, this._downloadFile, arg0), to_candid_GameMode_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMatchmakingRoom(to_candid_RoomType_n3(this._uploadFile, this._downloadFile, arg0), to_candid_GameMode_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return result;
        }
    }
    async createUser(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, arg1);
            return result;
        }
    }
    async deposit(arg0: number): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deposit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deposit(arg0);
            return result;
        }
    }
    async forfeitGame(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.forfeitGame(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.forfeitGame(arg0);
            return result;
        }
    }
    async generateReferralLink(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateReferralLink();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateReferralLink();
            return result;
        }
    }
    async getAllPlayers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlayers();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlayers();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableBots(): Promise<Array<BotConfig>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableBots();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableBots();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableGames(): Promise<Array<GameSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableGames();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableGames();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableRooms(): Promise<Array<MatchmakingRoom>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableRooms();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableRooms();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBalance(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBalance();
            return result;
        }
    }
    async getBoardState(arg0: Principal): Promise<BoardState> {
        if (this.processError) {
            try {
                const result = await this.actor.getBoardState(arg0);
                return from_candid_BoardState_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBoardState(arg0);
            return from_candid_BoardState_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBotMove(arg0: Principal, arg1: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getBotMove(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBotMove(arg0, arg1);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDemoCredits(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getDemoCredits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDemoCredits();
            return result;
        }
    }
    async getFeaturedGames(): Promise<Array<FeaturedGame>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedGames();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedGames();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGame(arg0: Principal): Promise<GameSession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGame(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGame(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMoveProbabilities(arg0: Principal): Promise<Array<MoveProbability>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMoveProbabilities(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMoveProbabilities(arg0);
            return result;
        }
    }
    async getOfficialWallets(): Promise<Array<OfficialWallet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOfficialWallets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOfficialWallets();
            return result;
        }
    }
    async getRoomState(arg0: Principal): Promise<MatchmakingRoom | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomState(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomState(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSpectatorCount(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getSpectatorCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSpectatorCount(arg0);
            return result;
        }
    }
    async getSpectatorReactions(arg0: Principal): Promise<Array<SpectatorReaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSpectatorReactions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSpectatorReactions(arg0);
            return result;
        }
    }
    async getSystemStats(): Promise<SystemStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getSystemStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSystemStats();
            return result;
        }
    }
    async getTokenSouls(arg0: Principal): Promise<Array<TokenSoul>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTokenSouls(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTokenSouls(arg0);
            return result;
        }
    }
    async getTransactionHistory(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionHistory();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionHistory();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWallet(): Promise<Wallet | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWallet();
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWallet();
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWinner(arg0: Principal): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWinner(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWinner(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async isFirstTime(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isFirstTime();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isFirstTime();
            return result;
        }
    }
    async isPremium(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isPremium();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isPremium();
            return result;
        }
    }
    async joinAsSpectator(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.joinAsSpectator(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinAsSpectator(arg0);
            return result;
        }
    }
    async joinGame(arg0: Principal, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.joinGame(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinGame(arg0, arg1);
            return result;
        }
    }
    async joinRoom(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.joinRoom(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinRoom(arg0);
            return result;
        }
    }
    async leaveRoom(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveRoom(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveRoom(arg0);
            return result;
        }
    }
    async leaveSpectator(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveSpectator(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveSpectator(arg0);
            return result;
        }
    }
    async moveToken(arg0: Principal, arg1: bigint, arg2: bigint): Promise<GameSession> {
        if (this.processError) {
            try {
                const result = await this.actor.moveToken(arg0, arg1, arg2);
                return from_candid_GameSession_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.moveToken(arg0, arg1, arg2);
            return from_candid_GameSession_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerBot(arg0: string, arg1: BotDifficulty): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.registerBot(arg0, to_candid_BotDifficulty_n41(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerBot(arg0, to_candid_BotDifficulty_n41(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async resetDemoCredits(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.resetDemoCredits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetDemoCredits();
            return result;
        }
    }
    async rollDice(arg0: Principal): Promise<{
        valid: boolean;
        value: bigint;
        seedHash: string;
        entropy: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.rollDice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rollDice(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async sendSpectatorReaction(arg0: Principal, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.sendSpectatorReaction(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendSpectatorReaction(arg0, arg1);
            return result;
        }
    }
    async updatePlayer(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlayer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlayer(arg0, arg1);
            return result;
        }
    }
    async upgradeToPremium(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.upgradeToPremium();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upgradeToPremium();
            return result;
        }
    }
    async withdraw(arg0: number): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.withdraw(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.withdraw(arg0);
            return result;
        }
    }
}
function from_candid_BoardState_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BoardState): BoardState {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_BotConfig_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BotConfig): BotConfig {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_BotDifficulty_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BotDifficulty): BotDifficulty {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_FeaturedGame_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeaturedGame): FeaturedGame {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_GameMode_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameMode): GameMode {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_GameSession_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameSession): GameSession {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_GameStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameStatus): GameStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_MatchmakingRoom_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchmakingRoom): MatchmakingRoom {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_RankedStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RankedStatus): RankedStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_RoomType_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoomType): RoomType {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GameSession]): GameSession | null {
    return value.length === 0 ? null : from_candid_GameSession_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MatchmakingRoom]): MatchmakingRoom | null {
    return value.length === 0 ? null : from_candid_MatchmakingRoom_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Wallet]): Wallet | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    balance: number;
    isPremium: boolean;
    difficulty: _BotDifficulty;
    name: string;
}): {
    principal: Principal;
    balance: number;
    isPremium: boolean;
    difficulty: BotDifficulty;
    name: string;
} {
    return {
        principal: value.principal,
        balance: value.balance,
        isPremium: value.isPremium,
        difficulty: from_candid_BotDifficulty_n12(_uploadFile, _downloadFile, value.difficulty),
        name: value.name
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    playerStates: Array<_PlayerState>;
    status: _GameStatus;
    betAmount: number;
    mode: _GameMode;
    createdAt: bigint;
    winner: [] | [Principal];
    isDemo: boolean;
    currentTurn: bigint;
    players: Array<Principal>;
    diceHistory: Array<_DiceRoll>;
    rankedStatus: _RankedStatus;
}): {
    id: Principal;
    playerStates: Array<PlayerState>;
    status: GameStatus;
    betAmount: number;
    mode: GameMode;
    createdAt: bigint;
    winner?: Principal;
    isDemo: boolean;
    currentTurn: bigint;
    players: Array<Principal>;
    diceHistory: Array<DiceRoll>;
    rankedStatus: RankedStatus;
} {
    return {
        id: value.id,
        playerStates: value.playerStates,
        status: from_candid_GameStatus_n17(_uploadFile, _downloadFile, value.status),
        betAmount: value.betAmount,
        mode: from_candid_GameMode_n19(_uploadFile, _downloadFile, value.mode),
        createdAt: value.createdAt,
        winner: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.winner)),
        isDemo: value.isDemo,
        currentTurn: value.currentTurn,
        players: value.players,
        diceHistory: value.diceHistory,
        rankedStatus: from_candid_RankedStatus_n21(_uploadFile, _downloadFile, value.rankedStatus)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    status: {
        active: null;
    } | {
        completed: null;
    } | {
        waiting: null;
    };
    creator: Principal;
    betAmount: number;
    createdAt: bigint;
    playerCount: bigint;
    isDemo: boolean;
    players: Array<Principal>;
    gameMode: _GameMode;
    roomType: _RoomType;
    maxPlayers: bigint;
}): {
    id: Principal;
    status: GameStatus;
    creator: Principal;
    betAmount: number;
    createdAt: bigint;
    playerCount: bigint;
    isDemo: boolean;
    players: Array<Principal>;
    gameMode: GameMode;
    roomType: RoomType;
    maxPlayers: bigint;
} {
    return {
        id: value.id,
        status: from_candid_variant_n18(_uploadFile, _downloadFile, value.status),
        creator: value.creator,
        betAmount: value.betAmount,
        createdAt: value.createdAt,
        playerCount: value.playerCount,
        isDemo: value.isDemo,
        players: value.players,
        gameMode: from_candid_GameMode_n19(_uploadFile, _downloadFile, value.gameMode),
        roomType: from_candid_RoomType_n26(_uploadFile, _downloadFile, value.roomType),
        maxPlayers: value.maxPlayers
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    betMultiplier: number;
    winStreakPlayer: [] | [Principal];
    state: string;
    glowIntensity: number;
}): {
    betMultiplier: number;
    winStreakPlayer?: Principal;
    state: string;
    glowIntensity: number;
} {
    return {
        betMultiplier: value.betMultiplier,
        winStreakPlayer: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.winStreakPlayer)),
        state: value.state,
        glowIntensity: value.glowIntensity
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _GameStatus;
    betAmount: number;
    spectatorCount: bigint;
    mode: _GameMode;
    gameId: Principal;
    playerCount: bigint;
}): {
    status: GameStatus;
    betAmount: number;
    spectatorCount: bigint;
    mode: GameMode;
    gameId: Principal;
    playerCount: bigint;
} {
    return {
        status: from_candid_GameStatus_n17(_uploadFile, _downloadFile, value.status),
        betAmount: value.betAmount,
        spectatorCount: value.spectatorCount,
        mode: from_candid_GameMode_n19(_uploadFile, _downloadFile, value.mode),
        gameId: value.gameId,
        playerCount: value.playerCount
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    description: string;
    timestamp: bigint;
    txType: {
        withdraw: null;
    } | {
        betLock: null;
    } | {
        betRefund: null;
    } | {
        deposit: null;
    } | {
        betWin: null;
    };
    amount: number;
}): {
    id: bigint;
    description: string;
    timestamp: bigint;
    txType: Variant_withdraw_betLock_betRefund_deposit_betWin;
    amount: number;
} {
    return {
        id: value.id,
        description: value.description,
        timestamp: value.timestamp,
        txType: from_candid_variant_n39(_uploadFile, _downloadFile, value.txType),
        amount: value.amount
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    referralCode: string;
    gamesPlayed: number;
    isPremium: boolean;
    name: string;
    createdAt: bigint;
    color: string;
    wins: number;
    losses: number;
    icpBalance: number;
    currentGame: [] | [Principal];
    avatarUrl: string;
    demoCredits: number;
    draws: number;
    lastActive: bigint;
}): {
    bio: string;
    referralCode: string;
    gamesPlayed: number;
    isPremium: boolean;
    name: string;
    createdAt: bigint;
    color: string;
    wins: number;
    losses: number;
    icpBalance: number;
    currentGame?: Principal;
    avatarUrl: string;
    demoCredits: number;
    draws: number;
    lastActive: bigint;
} {
    return {
        bio: value.bio,
        referralCode: value.referralCode,
        gamesPlayed: value.gamesPlayed,
        isPremium: value.isPremium,
        name: value.name,
        createdAt: value.createdAt,
        color: value.color,
        wins: value.wins,
        losses: value.losses,
        icpBalance: value.icpBalance,
        currentGame: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.currentGame)),
        avatarUrl: value.avatarUrl,
        demoCredits: value.demoCredits,
        draws: value.draws,
        lastActive: value.lastActive
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    easy: null;
} | {
    hard: null;
} | {
    medium: null;
}): BotDifficulty {
    return "easy" in value ? BotDifficulty.easy : "hard" in value ? BotDifficulty.hard : "medium" in value ? BotDifficulty.medium : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    completed: null;
} | {
    waiting: null;
}): GameStatus {
    return "active" in value ? GameStatus.active : "completed" in value ? GameStatus.completed : "waiting" in value ? GameStatus.waiting : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    magic: null;
} | {
    timed: null;
} | {
    challenge: null;
} | {
    advanced: null;
} | {
    experimental: null;
} | {
    custom: null;
} | {
    demo: null;
} | {
    team: null;
} | {
    superLudo: null;
} | {
    quick: null;
} | {
    tournament: null;
} | {
    classic: null;
} | {
    twoVsTwo: null;
} | {
    practice: null;
} | {
    bonus: null;
} | {
    master: null;
} | {
    copyClassic: null;
} | {
    copyFast: null;
}): GameMode {
    return "magic" in value ? GameMode.magic : "timed" in value ? GameMode.timed : "challenge" in value ? GameMode.challenge : "advanced" in value ? GameMode.advanced : "experimental" in value ? GameMode.experimental : "custom" in value ? GameMode.custom : "demo" in value ? GameMode.demo : "team" in value ? GameMode.team : "superLudo" in value ? GameMode.superLudo : "quick" in value ? GameMode.quick : "tournament" in value ? GameMode.tournament : "classic" in value ? GameMode.classic : "twoVsTwo" in value ? GameMode.twoVsTwo : "practice" in value ? GameMode.practice : "bonus" in value ? GameMode.bonus : "master" in value ? GameMode.master : "copyClassic" in value ? GameMode.copyClassic : "copyFast" in value ? GameMode.copyFast : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ranked: null;
} | {
    unranked: null;
}): RankedStatus {
    return "ranked" in value ? RankedStatus.ranked : "unranked" in value ? RankedStatus.unranked : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    privateRoom: null;
} | {
    isPublic: null;
}): RoomType {
    return "privateRoom" in value ? RoomType.privateRoom : "isPublic" in value ? RoomType.isPublic : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    withdraw: null;
} | {
    betLock: null;
} | {
    betRefund: null;
} | {
    deposit: null;
} | {
    betWin: null;
}): Variant_withdraw_betLock_betRefund_deposit_betWin {
    return "withdraw" in value ? Variant_withdraw_betLock_betRefund_deposit_betWin.withdraw : "betLock" in value ? Variant_withdraw_betLock_betRefund_deposit_betWin.betLock : "betRefund" in value ? Variant_withdraw_betLock_betRefund_deposit_betWin.betRefund : "deposit" in value ? Variant_withdraw_betLock_betRefund_deposit_betWin.deposit : "betWin" in value ? Variant_withdraw_betLock_betRefund_deposit_betWin.betWin : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GameSession>): Array<GameSession> {
    return value.map((x)=>from_candid_GameSession_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MatchmakingRoom>): Array<MatchmakingRoom> {
    return value.map((x)=>from_candid_MatchmakingRoom_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FeaturedGame>): Array<FeaturedGame> {
    return value.map((x)=>from_candid_FeaturedGame_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BotConfig>): Array<BotConfig> {
    return value.map((x)=>from_candid_BotConfig_n10(_uploadFile, _downloadFile, x));
}
function to_candid_BotDifficulty_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BotDifficulty): _BotDifficulty {
    return to_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function to_candid_GameMode_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameMode): _GameMode {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_RoomType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomType): _RoomType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameMode): {
    magic: null;
} | {
    timed: null;
} | {
    challenge: null;
} | {
    advanced: null;
} | {
    experimental: null;
} | {
    custom: null;
} | {
    demo: null;
} | {
    team: null;
} | {
    superLudo: null;
} | {
    quick: null;
} | {
    tournament: null;
} | {
    classic: null;
} | {
    twoVsTwo: null;
} | {
    practice: null;
} | {
    bonus: null;
} | {
    master: null;
} | {
    copyClassic: null;
} | {
    copyFast: null;
} {
    return value == GameMode.magic ? {
        magic: null
    } : value == GameMode.timed ? {
        timed: null
    } : value == GameMode.challenge ? {
        challenge: null
    } : value == GameMode.advanced ? {
        advanced: null
    } : value == GameMode.experimental ? {
        experimental: null
    } : value == GameMode.custom ? {
        custom: null
    } : value == GameMode.demo ? {
        demo: null
    } : value == GameMode.team ? {
        team: null
    } : value == GameMode.superLudo ? {
        superLudo: null
    } : value == GameMode.quick ? {
        quick: null
    } : value == GameMode.tournament ? {
        tournament: null
    } : value == GameMode.classic ? {
        classic: null
    } : value == GameMode.twoVsTwo ? {
        twoVsTwo: null
    } : value == GameMode.practice ? {
        practice: null
    } : value == GameMode.bonus ? {
        bonus: null
    } : value == GameMode.master ? {
        master: null
    } : value == GameMode.copyClassic ? {
        copyClassic: null
    } : value == GameMode.copyFast ? {
        copyFast: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomType): {
    privateRoom: null;
} | {
    isPublic: null;
} {
    return value == RoomType.privateRoom ? {
        privateRoom: null
    } : value == RoomType.isPublic ? {
        isPublic: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BotDifficulty): {
    easy: null;
} | {
    hard: null;
} | {
    medium: null;
} {
    return value == BotDifficulty.easy ? {
        easy: null
    } : value == BotDifficulty.hard ? {
        hard: null
    } : value == BotDifficulty.medium ? {
        medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
